### ISSUE TITLE
GB Test - Checklist 

### ISSUE THREAD

**Issue by DouglasAmarelo** [DouglasAmarelo/gb-test-checklist#1]
### Readme
- [ ] O Readme da aplicação descreve todos os passos necessários para o funcionamento da mesma.

### Commits

- [ ] A quantidade de commits é suficiente para o desenvolvimento da aplicação
- [ ] Através dos commits é possível acompanhar a evolução da aplicação e quiçá voltar em um _ponto X_ da aplicação
- [ ] Os commits contém uma qualidade descritiva das ações que foram feitas no projeto
- [ ] Os commits mantém consistência de formato e/ou informação

### URL's
- [ ] Todas as URL's da aplicação funcionam
- [ ] As URL's da aplicação podem ser compartilhadas e funcionam de maneira isolada
- [ ] Existe tratamento para erros na URL?
